### ISSUE TITLE
Create footer with the sponsors

### ISSUE THREAD

**Issue by fbaiodias** [sinfo/sinfo-webapp#1]
Should have the Exclusive and Maximum sponsor levels, as on https://sinfo.org/22

**Comment by miguelpfaraujo** [comment]
And some Partners, the ones that have maximum publicity pack

**Comment by palma21** [comment]
It's in the comments Exclusive and Maximum _advertisement_ levels ;)

2015-02-16 10:53 GMT+00:00 Miguel Araújo notifications@github.com:

> And some Partners, the ones that have maximum publicity pack
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sinfo/cannon-webapp/issues/1#issuecomment-74490534.

## 

_Jorge Palma_
Nº 67024
MEIC-Alameda
