### ISSUE TITLE
Implement Speakers Section

### ISSUE THREAD

**Issue by johnytiago** [sinfo/sinfo-webapp#30]
Implement speakers section.
We'll use the 4 columns and square component template.
The Hover effect we would like to is the one you can see [here](http://demo.deviserweb.com/eventer/version/light/transparent-color-image-bg/style-1/index.html#section-4).
Zoom + Blue Overlay + Company logo
Ask Zé for the blue color code.

**Comment by josepedrocandido** [comment]
Blue Color Code: #0C5585
